{% set version = "1.41" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: 0407035fe3c6644387d48cff1467d5aa9feff814d07372b78677ed0ee3ed7095

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  license_file: LICENSE
  summary: Serialization based on ast.literal_eval

extra:
  recipe-maintainers:
    - irmen
    - whart222
