{% set version = "1.30" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: 74af57fdc2a5f69b2f5702c6ecc71815d1b6a0505690430407302b1727d50d59

build:
  number: 0
  noarch: python 
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5

test:
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  license_file: LICENSE
  summary: 'Serialization based on ast.literal_eval'

extra:
  recipe-maintainers:
    - irmen
    - whart222
    - Juanlu001
